# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       ce-backgrounds
Summary:    OpenShellfish backgrounds
Version:    0.3
Release:    1
Group:      Applications/Multimedia
License:    LGPLv2
BuildArch:  noarch
Source0:    splash-osf-800x480.png
Source1:    shutdown-osf-800x480.png
Source100:  ce-backgrounds.yaml
Provides:   openshellfish-backgrounds
Obsoletes:   generic-backgrounds


%description
The %{name} package contains artwork for OpenShellfish.




%prep
# No setup

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
install -D -m 644 %{SOURCE0} %{buildroot}/%{_datadir}/plymouth/splash-osf-800x480.png
install -D -m 644 %{SOURCE1} %{buildroot}/%{_datadir}/plymouth/shutdown-osf-800x480.png
ln -s splash-osf-800x480.png %{buildroot}/%{_datadir}/plymouth/splash.png
ln -s shutdown-osf-800x480.png %{buildroot}/%{_datadir}/plymouth/halt.png
ln -s shutdown-osf-800x480.png %{buildroot}/%{_datadir}/plymouth/poweroff.png
ln -s shutdown-osf-800x480.png %{buildroot}/%{_datadir}/plymouth/reboot.png
# << install pre

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/plymouth/splash-osf-800x480.png
%{_datadir}/plymouth/shutdown-osf-800x480.png
%{_datadir}/plymouth/splash.png
%{_datadir}/plymouth/halt.png
%{_datadir}/plymouth/poweroff.png
%{_datadir}/plymouth/reboot.png
# << files


